### ISSUE TITLE
Incompatibility with pip 10.0.0

### ISSUE THREAD

**Issue by sajanalexander** [Aloomaio/python-sdk#12]
The pip.req module was changed to pip._internal.req in pip 10.0.0.  Installing this package via pip 10.0.0 causes the error: 

```
Collecting alooma-pysdk==2.0.1.3
  Downloading https://files.pythonhosted.org/packages/d6/7f/3b6a5293992203e946cf2601a653d22ca5f47336e469d6284ddce8137b5d/alooma_pysdk-2.0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v3/mb7klyrd55v6nfqb4qk4zst40000gn/T/pip-install-1FzMMv/alooma-pysdk/setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
```

**Comment by yuvalbar** [comment]
Closed following merging this PR: https://github.com/Aloomaio/python-sdk/pull/13
